### PR TITLE
Bugfix #182315539 - Add organism in payload field - rebased

### PR DESCRIPTION
**Pull request by pcm32**
Given that the rebase on #37 was a bit chaotic, I opened this to check.

### CODE REVIEW

**Comment by pcm32** [comment]
Why remove the config sets? Doing all from the default config set used to generate issues as I can remember. Could we do it after the merge of this brnach, so that the repo reflects what is currently on the servers (which used the config set parts)?

**Comment by pcm32** [comment]
Why that test keeps failing is puzzling, as the same call happens before and after without failing. I'm looking forward to merge this as many other repos depend on it and need merging as well.

**Comment by pcm32** [comment]
As the last few commits show, many of the tests were actually failing silently and the missing file only uncovered the failure (which was due to tests being in /opt and bin in /usr/local/bin in the container. Adding an extra mount fixed those errors. Now I suspect that the one failing is due to some issue with the actual testing logic (I suspect that that check shouldn't be there, as it is actively looking for a specific entry from a condensed that might have not been actually deleted from the index).

**Comment by pcm32** [comment]
I ended up removing that test from there since:
- the deletion that was being checked was already checked in test before
- the script to check for content is not fit for checking for lack of content as it is currently written, because of the timeout loop (redoing the check everytime it gets zero documents, which is the result when trying to check for lack of content).

**Comment by pcm32** [comment]
I will merge this since #37 was approved already and here only minor things were fixed in terms of tests.

**Review by pmb59 — APPROVED** [review]
LGTM

**Pull request merged**
