### PR TITLE
gene2experiment index

### PR DESCRIPTION
**Pull request by pcm32**
This PR adds a new solr index setup and generation for SCXA experiments, which allows to join gene identifiers and experiment accessions. Includes passing test and documentation.

### CODE REVIEW

**Comment by pcm32** [comment]
Ok, all tests passing now.. had a non-cloud solr glitch on travis.

**Comment by pcm32** [comment]
If any of the two could give me a review please, I would really appreciate. This is ready to go, to be integrated into atlas prod dev.

**Comment by pcm32** [comment]
Besides automated tests, this has been tested now as well to work adequately within the entire scxa prod pipeline (test env). This is ready to be merged in my view, if you could review @suhaibMo I would really appreciate it.

**Review by suhaibMo — APPROVED** [review]
Overall looks good. In travis the two CI tests are deployed PR and push commit. Could you highlight the differences for my understanding. Looking at log the feature branch and  refs/pull/10/merge.

**Comment by pcm32** [comment]
Well spotted @suhaibMo, there is no real difference really, we are just wasting Travis resources!

**Comment by pcm32** [comment]
Thanks @suhaibMo!

**Pull request merged**
