### PR TITLE
Make stated JSONL really JSONLs

### PR DESCRIPTION
**Pull request by pcm32**
On the previous set of changes JSONL usage was introduced, but what we noticed on the servers was that files were not really JSONLs but normal JSON files. This should correct that. This is in the hope of making the JSON merging through jq operation faster.

### CODE REVIEW

**Comment by pcm32** [comment]
While this fixes the JSONL-ness, merge in jq is still relatively slow even for small experiments. We might be better off merging sorted TSVs with join, unless that jq has an indexing feature that we could use to speed this up.

**Comment by pcm32** [comment]
Last approach for merge is actually wrong, it is an an inner join.... we need a left join where the condensed is on the left.

**Comment by pinin4fjords** [comment]
Maybe the 'elaborate' function used here? https://github.com/stedolan/jq/issues/1090#issuecomment-388173282

**Comment by pcm32** [comment]
Could be, you need to adapt it though to receive two files, or merge everything before passing it.

**Review by alfonsomunozpomer — COMMENTED** [review]
I tested the script before applying this change and all the three generated files are JSONLs, so I’m not sure the title of this PR is accurate.

With, e.g. E-MTAB-5061:

`E-MTAB-5061.condensed-sdrf.jsonl`:
```jsonl
{ "experiment_accession": "E-MTAB-5061",
 "cell_id": "ERR1630013",
 "characteristic_name": "age",
 "characteristic_value": "43 year",
 "ontology_annotation": "" }
{ "experiment_accession": "E-MTAB-5061",
 "cell_id": "ERR1630013",
 "characteristic_name": "biosource_provider",
 "characteristic_value": "Prodo Laboratories Inc",
 "ontology_annotation": "" }
{ "experiment_accession": "E-MTAB-5061",
 "cell_id": "ERR1630013",
...
```

`E-MTAB-5061.condensed-sdrf.cell-type-wheel.jsonl`:
```jsonl
{
  "cell_id": "ERR1630013",
  "experiment_accession": "E-MTAB-5061",
  "ctw_organism": "Homo sapiens",
  "ctw_organism_part": "pancreas",
  "ctw_cell_type": "islet of Langerhans"
}
{
  "cell_id": "ERR1630014",
  "experiment_accession": "E-MTAB-5061",
  "ctw_organism": "Homo sapiens",
  "ctw_organism_part": "pancreas",
  "ctw_cell_type": "pancreatic D cell"
}
{
  "cell_id": "ERR1630015",
  "experiment_accession": "E-MTAB-5061",
...
```

`E-MTAB-5061.condensed-sdrf.ctw-enriched.jsonl`:
```jsonl
 {
  "experiment_accession": "E-MTAB-5061",
  "cell_id": "ERR1630013",
  "characteristic_name": "age",
  "characteristic_value": "43 year",
  "ctw_organism": "Homo sapiens",
  "ctw_organism_part": "pancreas",
  "ctw_cell_type": "islet of Langerhans"
}
{
  "experiment_accession": "E-MTAB-5061",
  "cell_id": "ERR1630013",
  "characteristic_name": "biosource_provider",
  "characteristic_value": "Prodo Laboratories Inc",
  "ctw_organism": "Homo sapiens",
  "ctw_organism_part": "pancreas",
  "ctw_cell_type": "islet of Langerhans"
}
{
  "experiment_accession": "E-MTAB-5061",
  "cell_id": "ERR1630013",
...
```

**Comment by alfonsomunozpomer** [comment]
If the goal here is to make the merge step faster, I think `jq` can take us only this far and we’re better off looking at alternatives like Node.js.

**Comment by alfonsomunozpomer** [comment]
I hacked a quick script in Node.js and, without much consideration for efficiency, for E-MTAB-5061 I `time`d it and got this:
```
real	0m1.325s
user	0m1.932s
sys	0m1.109s
```

The original `jq` script:
```
real	2m55.757s
user	2m59.114s
sys	0m0.197s
```

**Comment by alfonsomunozpomer** [comment]
Some more figures below. E-CURD-4 is three times bigger than E-MTAB-5061 and is the biggest condensed SDRF we’ve got in our test datasets. I looked at our current experiments and E-HCAD-4 is by far the biggest one. The second one is ~500M, then we have  a few outliers ~200M, but most are way below 100M.

### E-CURD-4, 16M, 161,575 records:
**Node.js**
```
real	0m4.690s
user	0m6.515s
sys	0m4.167s
```

**`jq`**
```
real	30m55.358s
user	31m4.251s
sys	0m0.718s
```

### E-HCAD-4, 808M, 7,698,442 records:
**Node.js**
```
real	2m45.878s
user	2m14.401s
sys	0m43.961s
```

**`jq`**
```
real	TBA
user	TBA
sys	TBA
```

This is the time taken only by the merge step. In the case of E-HCAD-4, the previous steps that transform the TSV file to JSONL and extract the cell type wheel fields take about 1m30s and 3m, respectively (which are anecdotical when compared to the last step!).

My takeaway here is that `jq` isn’t very efficient, or at the very least it takes considerable effort to make efficient scripts (it might as well be that I’m not experienced enough). Node.js, on the other hand, has as one of its foundational goals a very fast and efficient I/O subsystem. The script I did is about 15 LOC and can be further optimised if necessary (my guess is that we can still shave off 15%-20% of running time).

Of course, this isn’t the whole story because in the Node.js script I created an additional object keyed by cell ID which is effectively a dictionary (with the help of the Lodash library you can do it in one line). Now, say what you want about imperative programming, but in plain JS I can tell how I want to do things, whereas `jq` is mainly declarative and from the top of my head I don’t know how I’d go about doing the same thing.

 As it’s often the case, the right tool for the right job. I don’t think spending more time in the `jq` script is going to be worthwile. As it is, unless we break the condensed SDRF into chunks, it doesn’t scale. Let’s discuss this any time this week.

**Comment by pcm32** [comment]
The files are not JSONL if they are not a single line per JSON object (not single field). Every line needs to be an independent JSON object. Before this PR, JSONs were using various lines per JSON object, so not JSONLs. We noticed this when we had to inspect results in the server due to the long time of the merge step.

So the examples above @alfonsomunozpomer are AFAIK not JSONL.

**Comment by pcm32** [comment]
The inner join above did E-CURD-2 in seconds, we never saw it finish for the previous implementation (even after 15 minutes), so I suspect it is possible to make it scale in jq, but I don't mind.

**Comment by pcm32** [comment]
If you add to this PR @alfonsomunozpomer the Node alternative and we remove the jq merger, we can attempt a load with Jon, thanks!

**Comment by pcm32** [comment]
Or the new jq solution that you mentioned that you had this morning,.

**Comment by alfonsomunozpomer** [comment]
> So the examples above @alfonsomunozpomer are AFAIK not JSONL.

Yep, you’re right. I was thinking about `json-seq`, which is the actual MIME type (JSONL being a specific way of doing `json-seq`). `jq` and Solr can deal with `json-seq` and I was using the terms interchangeably. I can see that not sticking to JSONL can cause problems in `solr-jsonl-chunk-loader.sh`, though.

> The inner join above did E-CURD-2 in seconds, we never saw it finish for the previous implementation (even after 15 minutes),

In the case of E-HCAD-4 after 20 hours or so the script had written out about 50MB of a total of 2.2GB, so you do the math. It turns out that by doing a `map(select ...)` I suspect that the running time is proportional to the number of SDRF entries times the number of cells (it iterates over the whole array every time you add CTW fields). In the case of E-HCAD-4 it’s 7.7M × 600k. So not good.

> so I suspect it is possible to make it scale in jq, but I don't mind.

Yes we can! Check the latest commits and let me know.

**Comment by pcm32** [comment]
@pinin4fjords @alfonsomunozpomer I think that we have used this now as it is and v6 loaded like this is available on public, are we fine to merge it? Can both of you approve please? Thanks.

**Review by pinin4fjords — APPROVED** [review]

**Review by alfonsomunozpomer — APPROVED** [review]

**Pull request merged**
